// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Bid bid
//
// swagger:model bid
type Bid struct {

	// amount to buy
	AmountToBuy float32 `json:"amount_to_buy,omitempty"`

	// bid id
	BidID int64 `json:"bid_id,omitempty"`

	// bought amount
	BoughtAmount float32 `json:"bought_amount,omitempty"`

	// buy speed
	BuySpeed float32 `json:"buy_speed,omitempty"`

	// max price
	MaxPrice float32 `json:"max_price,omitempty"`

	// min price
	MinPrice float32 `json:"min_price,omitempty"`

	// user id
	UserID int64 `json:"user_id,omitempty"`
}

// Validate validates this bid
func (m *Bid) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this bid based on context it is used
func (m *Bid) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Bid) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Bid) UnmarshalBinary(b []byte) error {
	var res Bid
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
