// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/h4x4d/crypto-market/payment/internal/models"
)

// GetTransactionsPurchaseOKCode is the HTTP code returned for type GetTransactionsPurchaseOK
const GetTransactionsPurchaseOKCode int = 200

/*
GetTransactionsPurchaseOK Success operation

swagger:response getTransactionsPurchaseOK
*/
type GetTransactionsPurchaseOK struct {

	/*
	  In: Body
	*/
	Payload []*GetTransactionsPurchaseOKBodyItems0 `json:"body,omitempty"`
}

// NewGetTransactionsPurchaseOK creates GetTransactionsPurchaseOK with default headers values
func NewGetTransactionsPurchaseOK() *GetTransactionsPurchaseOK {

	return &GetTransactionsPurchaseOK{}
}

// WithPayload adds the payload to the get transactions purchase o k response
func (o *GetTransactionsPurchaseOK) WithPayload(payload []*GetTransactionsPurchaseOKBodyItems0) *GetTransactionsPurchaseOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get transactions purchase o k response
func (o *GetTransactionsPurchaseOK) SetPayload(payload []*GetTransactionsPurchaseOKBodyItems0) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTransactionsPurchaseOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*GetTransactionsPurchaseOKBodyItems0, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetTransactionsPurchaseUnauthorizedCode is the HTTP code returned for type GetTransactionsPurchaseUnauthorized
const GetTransactionsPurchaseUnauthorizedCode int = 401

/*
GetTransactionsPurchaseUnauthorized Unauthorized

swagger:response getTransactionsPurchaseUnauthorized
*/
type GetTransactionsPurchaseUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetTransactionsPurchaseUnauthorized creates GetTransactionsPurchaseUnauthorized with default headers values
func NewGetTransactionsPurchaseUnauthorized() *GetTransactionsPurchaseUnauthorized {

	return &GetTransactionsPurchaseUnauthorized{}
}

// WithPayload adds the payload to the get transactions purchase unauthorized response
func (o *GetTransactionsPurchaseUnauthorized) WithPayload(payload *models.Error) *GetTransactionsPurchaseUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get transactions purchase unauthorized response
func (o *GetTransactionsPurchaseUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTransactionsPurchaseUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetTransactionsPurchaseConflictCode is the HTTP code returned for type GetTransactionsPurchaseConflict
const GetTransactionsPurchaseConflictCode int = 409

/*
GetTransactionsPurchaseConflict Incorrect data

swagger:response getTransactionsPurchaseConflict
*/
type GetTransactionsPurchaseConflict struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetTransactionsPurchaseConflict creates GetTransactionsPurchaseConflict with default headers values
func NewGetTransactionsPurchaseConflict() *GetTransactionsPurchaseConflict {

	return &GetTransactionsPurchaseConflict{}
}

// WithPayload adds the payload to the get transactions purchase conflict response
func (o *GetTransactionsPurchaseConflict) WithPayload(payload *models.Error) *GetTransactionsPurchaseConflict {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get transactions purchase conflict response
func (o *GetTransactionsPurchaseConflict) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTransactionsPurchaseConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(409)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
