// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CancelBidHandlerFunc turns a function with the right signature into a cancel bid handler
type CancelBidHandlerFunc func(CancelBidParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn CancelBidHandlerFunc) Handle(params CancelBidParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// CancelBidHandler interface for that can handle valid cancel bid params
type CancelBidHandler interface {
	Handle(CancelBidParams, interface{}) middleware.Responder
}

// NewCancelBid creates a new http.Handler for the cancel bid operation
func NewCancelBid(ctx *middleware.Context, handler CancelBidHandler) *CancelBid {
	return &CancelBid{Context: ctx, Handler: handler}
}

/*
	CancelBid swagger:route DELETE /market/{bid_id} cancelBid

Cancel bid
*/
type CancelBid struct {
	Context *middleware.Context
	Handler CancelBidHandler
}

func (o *CancelBid) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewCancelBidParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
