// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// NewGetTransactionsPurchaseParams creates a new GetTransactionsPurchaseParams object
//
// There are no default values defined in the spec.
func NewGetTransactionsPurchaseParams() GetTransactionsPurchaseParams {

	return GetTransactionsPurchaseParams{}
}

// GetTransactionsPurchaseParams contains all the bound params for the get transactions purchase operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetTransactionsPurchase
type GetTransactionsPurchaseParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Filter purchases from this date (ISO 8601)
	  In: query
	*/
	DateFrom *strfmt.DateTime
	/*Filter purchases up to this date (ISO 8601)
	  In: query
	*/
	DateTo *strfmt.DateTime
	/*Filter by purchase status
	  In: query
	*/
	Status *string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetTransactionsPurchaseParams() beforehand.
func (o *GetTransactionsPurchaseParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qDateFrom, qhkDateFrom, _ := qs.GetOK("date_from")
	if err := o.bindDateFrom(qDateFrom, qhkDateFrom, route.Formats); err != nil {
		res = append(res, err)
	}

	qDateTo, qhkDateTo, _ := qs.GetOK("date_to")
	if err := o.bindDateTo(qDateTo, qhkDateTo, route.Formats); err != nil {
		res = append(res, err)
	}

	qStatus, qhkStatus, _ := qs.GetOK("status")
	if err := o.bindStatus(qStatus, qhkStatus, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindDateFrom binds and validates parameter DateFrom from query.
func (o *GetTransactionsPurchaseParams) bindDateFrom(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}

	// Format: date-time
	value, err := formats.Parse("date-time", raw)
	if err != nil {
		return errors.InvalidType("date_from", "query", "strfmt.DateTime", raw)
	}
	o.DateFrom = (value.(*strfmt.DateTime))

	if err := o.validateDateFrom(formats); err != nil {
		return err
	}

	return nil
}

// validateDateFrom carries on validations for parameter DateFrom
func (o *GetTransactionsPurchaseParams) validateDateFrom(formats strfmt.Registry) error {

	if err := validate.FormatOf("date_from", "query", "date-time", o.DateFrom.String(), formats); err != nil {
		return err
	}
	return nil
}

// bindDateTo binds and validates parameter DateTo from query.
func (o *GetTransactionsPurchaseParams) bindDateTo(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}

	// Format: date-time
	value, err := formats.Parse("date-time", raw)
	if err != nil {
		return errors.InvalidType("date_to", "query", "strfmt.DateTime", raw)
	}
	o.DateTo = (value.(*strfmt.DateTime))

	if err := o.validateDateTo(formats); err != nil {
		return err
	}

	return nil
}

// validateDateTo carries on validations for parameter DateTo
func (o *GetTransactionsPurchaseParams) validateDateTo(formats strfmt.Registry) error {

	if err := validate.FormatOf("date_to", "query", "date-time", o.DateTo.String(), formats); err != nil {
		return err
	}
	return nil
}

// bindStatus binds and validates parameter Status from query.
func (o *GetTransactionsPurchaseParams) bindStatus(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.Status = &raw

	if err := o.validateStatus(formats); err != nil {
		return err
	}

	return nil
}

// validateStatus carries on validations for parameter Status
func (o *GetTransactionsPurchaseParams) validateStatus(formats strfmt.Registry) error {

	if err := validate.EnumCase("status", "query", *o.Status, []interface{}{"finished", "processing", "cancelled"}, true); err != nil {
		return err
	}

	return nil
}
