// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"encoding/json"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GetTransactionsPurchaseHandlerFunc turns a function with the right signature into a get transactions purchase handler
type GetTransactionsPurchaseHandlerFunc func(GetTransactionsPurchaseParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetTransactionsPurchaseHandlerFunc) Handle(params GetTransactionsPurchaseParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetTransactionsPurchaseHandler interface for that can handle valid get transactions purchase params
type GetTransactionsPurchaseHandler interface {
	Handle(GetTransactionsPurchaseParams, interface{}) middleware.Responder
}

// NewGetTransactionsPurchase creates a new http.Handler for the get transactions purchase operation
func NewGetTransactionsPurchase(ctx *middleware.Context, handler GetTransactionsPurchaseHandler) *GetTransactionsPurchase {
	return &GetTransactionsPurchase{Context: ctx, Handler: handler}
}

/*
	GetTransactionsPurchase swagger:route GET /transactions/purchase getTransactionsPurchase

# Get purchase history

Returns all user's purchase
*/
type GetTransactionsPurchase struct {
	Context *middleware.Context
	Handler GetTransactionsPurchaseHandler
}

func (o *GetTransactionsPurchase) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetTransactionsPurchaseParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// GetTransactionsPurchaseBody get transactions purchase body
//
// swagger:model GetTransactionsPurchaseBody
type GetTransactionsPurchaseBody struct {

	// date from
	DateFrom string `json:"date_from,omitempty"`

	// date to
	DateTo string `json:"date_to,omitempty"`

	// status
	// Enum: ["finished","processing","cancelled"]
	Status string `json:"status,omitempty"`
}

// Validate validates this get transactions purchase body
func (o *GetTransactionsPurchaseBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var getTransactionsPurchaseBodyTypeStatusPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["finished","processing","cancelled"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		getTransactionsPurchaseBodyTypeStatusPropEnum = append(getTransactionsPurchaseBodyTypeStatusPropEnum, v)
	}
}

const (

	// GetTransactionsPurchaseBodyStatusFinished captures enum value "finished"
	GetTransactionsPurchaseBodyStatusFinished string = "finished"

	// GetTransactionsPurchaseBodyStatusProcessing captures enum value "processing"
	GetTransactionsPurchaseBodyStatusProcessing string = "processing"

	// GetTransactionsPurchaseBodyStatusCancelled captures enum value "cancelled"
	GetTransactionsPurchaseBodyStatusCancelled string = "cancelled"
)

// prop value enum
func (o *GetTransactionsPurchaseBody) validateStatusEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, getTransactionsPurchaseBodyTypeStatusPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (o *GetTransactionsPurchaseBody) validateStatus(formats strfmt.Registry) error {
	if swag.IsZero(o.Status) { // not required
		return nil
	}

	// value enum
	if err := o.validateStatusEnum("body"+"."+"status", "body", o.Status); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this get transactions purchase body based on context it is used
func (o *GetTransactionsPurchaseBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetTransactionsPurchaseBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetTransactionsPurchaseBody) UnmarshalBinary(b []byte) error {
	var res GetTransactionsPurchaseBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

// GetTransactionsPurchaseOKBodyItems0 get transactions purchase o k body items0
//
// swagger:model GetTransactionsPurchaseOKBodyItems0
type GetTransactionsPurchaseOKBodyItems0 struct {

	// amount from
	AmountFrom string `json:"amount_from,omitempty"`

	// amount to
	AmountTo string `json:"amount_to,omitempty"`

	// currency from
	CurrencyFrom string `json:"currency_from,omitempty"`

	// currency to
	CurrencyTo string `json:"currency_to,omitempty"`

	// date
	Date string `json:"date,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// status
	// Enum: ["finished","processing","cancelled"]
	Status string `json:"status,omitempty"`
}

// Validate validates this get transactions purchase o k body items0
func (o *GetTransactionsPurchaseOKBodyItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var getTransactionsPurchaseOKBodyItems0TypeStatusPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["finished","processing","cancelled"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		getTransactionsPurchaseOKBodyItems0TypeStatusPropEnum = append(getTransactionsPurchaseOKBodyItems0TypeStatusPropEnum, v)
	}
}

const (

	// GetTransactionsPurchaseOKBodyItems0StatusFinished captures enum value "finished"
	GetTransactionsPurchaseOKBodyItems0StatusFinished string = "finished"

	// GetTransactionsPurchaseOKBodyItems0StatusProcessing captures enum value "processing"
	GetTransactionsPurchaseOKBodyItems0StatusProcessing string = "processing"

	// GetTransactionsPurchaseOKBodyItems0StatusCancelled captures enum value "cancelled"
	GetTransactionsPurchaseOKBodyItems0StatusCancelled string = "cancelled"
)

// prop value enum
func (o *GetTransactionsPurchaseOKBodyItems0) validateStatusEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, getTransactionsPurchaseOKBodyItems0TypeStatusPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (o *GetTransactionsPurchaseOKBodyItems0) validateStatus(formats strfmt.Registry) error {
	if swag.IsZero(o.Status) { // not required
		return nil
	}

	// value enum
	if err := o.validateStatusEnum("status", "body", o.Status); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this get transactions purchase o k body items0 based on context it is used
func (o *GetTransactionsPurchaseOKBodyItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetTransactionsPurchaseOKBodyItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetTransactionsPurchaseOKBodyItems0) UnmarshalBinary(b []byte) error {
	var res GetTransactionsPurchaseOKBodyItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
