// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/h4x4d/crypto-market/main/internal/models"
)

// GetBidsOKCode is the HTTP code returned for type GetBidsOK
const GetBidsOKCode int = 200

/*
GetBidsOK Successful operation

swagger:response getBidsOK
*/
type GetBidsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Bid `json:"body,omitempty"`
}

// NewGetBidsOK creates GetBidsOK with default headers values
func NewGetBidsOK() *GetBidsOK {

	return &GetBidsOK{}
}

// WithPayload adds the payload to the get bids o k response
func (o *GetBidsOK) WithPayload(payload []*models.Bid) *GetBidsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get bids o k response
func (o *GetBidsOK) SetPayload(payload []*models.Bid) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBidsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Bid, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetBidsForbiddenCode is the HTTP code returned for type GetBidsForbidden
const GetBidsForbiddenCode int = 403

/*
GetBidsForbidden No access

swagger:response getBidsForbidden
*/
type GetBidsForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetBidsForbidden creates GetBidsForbidden with default headers values
func NewGetBidsForbidden() *GetBidsForbidden {

	return &GetBidsForbidden{}
}

// WithPayload adds the payload to the get bids forbidden response
func (o *GetBidsForbidden) WithPayload(payload *models.Error) *GetBidsForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get bids forbidden response
func (o *GetBidsForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBidsForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
