// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/h4x4d/crypto-market/main/internal/models"
)

// GetTransactionsPurchaseHandlerFunc turns a function with the right signature into a get transactions purchase handler
type GetTransactionsPurchaseHandlerFunc func(GetTransactionsPurchaseParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn GetTransactionsPurchaseHandlerFunc) Handle(params GetTransactionsPurchaseParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// GetTransactionsPurchaseHandler interface for that can handle valid get transactions purchase params
type GetTransactionsPurchaseHandler interface {
	Handle(GetTransactionsPurchaseParams, *models.User) middleware.Responder
}

// NewGetTransactionsPurchase creates a new http.Handler for the get transactions purchase operation
func NewGetTransactionsPurchase(ctx *middleware.Context, handler GetTransactionsPurchaseHandler) *GetTransactionsPurchase {
	return &GetTransactionsPurchase{Context: ctx, Handler: handler}
}

/*
	GetTransactionsPurchase swagger:route GET /transactions/purchase getTransactionsPurchase

# Get purchase history

Returns the user's purchase history with optional filters
*/
type GetTransactionsPurchase struct {
	Context *middleware.Context
	Handler GetTransactionsPurchaseHandler
}

func (o *GetTransactionsPurchase) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetTransactionsPurchaseParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
