// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"encoding/json"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PostTransactionsDepositHandlerFunc turns a function with the right signature into a post transactions deposit handler
type PostTransactionsDepositHandlerFunc func(PostTransactionsDepositParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PostTransactionsDepositHandlerFunc) Handle(params PostTransactionsDepositParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PostTransactionsDepositHandler interface for that can handle valid post transactions deposit params
type PostTransactionsDepositHandler interface {
	Handle(PostTransactionsDepositParams, interface{}) middleware.Responder
}

// NewPostTransactionsDeposit creates a new http.Handler for the post transactions deposit operation
func NewPostTransactionsDeposit(ctx *middleware.Context, handler PostTransactionsDepositHandler) *PostTransactionsDeposit {
	return &PostTransactionsDeposit{Context: ctx, Handler: handler}
}

/*
	PostTransactionsDeposit swagger:route POST /transactions/deposit postTransactionsDeposit

# Deposit request

Creates a request to deposit cryptocurrency to the user's account
*/
type PostTransactionsDeposit struct {
	Context *middleware.Context
	Handler PostTransactionsDepositHandler
}

func (o *PostTransactionsDeposit) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostTransactionsDepositParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// PostTransactionsDepositBody post transactions deposit body
//
// swagger:model PostTransactionsDepositBody
type PostTransactionsDepositBody struct {

	// amount
	// Example: 100.5
	// Required: true
	// Minimum: 0
	Amount *float32 `json:"amount"`

	// currency
	// Example: USDT
	// Required: true
	// Enum: ["USDT","BTC"]
	Currency *string `json:"currency"`
}

// Validate validates this post transactions deposit body
func (o *PostTransactionsDepositBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateAmount(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateCurrency(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostTransactionsDepositBody) validateAmount(formats strfmt.Registry) error {

	if err := validate.Required("body"+"."+"amount", "body", o.Amount); err != nil {
		return err
	}

	if err := validate.Minimum("body"+"."+"amount", "body", float64(*o.Amount), 0, false); err != nil {
		return err
	}

	return nil
}

var postTransactionsDepositBodyTypeCurrencyPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["USDT","BTC"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		postTransactionsDepositBodyTypeCurrencyPropEnum = append(postTransactionsDepositBodyTypeCurrencyPropEnum, v)
	}
}

const (

	// PostTransactionsDepositBodyCurrencyUSDT captures enum value "USDT"
	PostTransactionsDepositBodyCurrencyUSDT string = "USDT"

	// PostTransactionsDepositBodyCurrencyBTC captures enum value "BTC"
	PostTransactionsDepositBodyCurrencyBTC string = "BTC"
)

// prop value enum
func (o *PostTransactionsDepositBody) validateCurrencyEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, postTransactionsDepositBodyTypeCurrencyPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (o *PostTransactionsDepositBody) validateCurrency(formats strfmt.Registry) error {

	if err := validate.Required("body"+"."+"currency", "body", o.Currency); err != nil {
		return err
	}

	// value enum
	if err := o.validateCurrencyEnum("body"+"."+"currency", "body", *o.Currency); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this post transactions deposit body based on context it is used
func (o *PostTransactionsDepositBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostTransactionsDepositBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostTransactionsDepositBody) UnmarshalBinary(b []byte) error {
	var res PostTransactionsDepositBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

// PostTransactionsDepositOKBody post transactions deposit o k body
// Example: {"address":"0x1234567890abcdef1234567890abcdef12345678","id":"tx_dep_123456","status":"pending"}
//
// swagger:model PostTransactionsDepositOKBody
type PostTransactionsDepositOKBody struct {

	// address
	// Example: 0x1234567890abcdef1234567890abcdef12345678
	// Required: true
	Address *string `json:"address"`

	// id
	// Example: tx_dep_123456
	// Required: true
	ID *string `json:"id"`

	// status
	// Example: pending
	// Required: true
	// Enum: ["finished","processing","pending"]
	Status *string `json:"status"`
}

// Validate validates this post transactions deposit o k body
func (o *PostTransactionsDepositOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateAddress(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostTransactionsDepositOKBody) validateAddress(formats strfmt.Registry) error {

	if err := validate.Required("postTransactionsDepositOK"+"."+"address", "body", o.Address); err != nil {
		return err
	}

	return nil
}

func (o *PostTransactionsDepositOKBody) validateID(formats strfmt.Registry) error {

	if err := validate.Required("postTransactionsDepositOK"+"."+"id", "body", o.ID); err != nil {
		return err
	}

	return nil
}

var postTransactionsDepositOKBodyTypeStatusPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["finished","processing","pending"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		postTransactionsDepositOKBodyTypeStatusPropEnum = append(postTransactionsDepositOKBodyTypeStatusPropEnum, v)
	}
}

const (

	// PostTransactionsDepositOKBodyStatusFinished captures enum value "finished"
	PostTransactionsDepositOKBodyStatusFinished string = "finished"

	// PostTransactionsDepositOKBodyStatusProcessing captures enum value "processing"
	PostTransactionsDepositOKBodyStatusProcessing string = "processing"

	// PostTransactionsDepositOKBodyStatusPending captures enum value "pending"
	PostTransactionsDepositOKBodyStatusPending string = "pending"
)

// prop value enum
func (o *PostTransactionsDepositOKBody) validateStatusEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, postTransactionsDepositOKBodyTypeStatusPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (o *PostTransactionsDepositOKBody) validateStatus(formats strfmt.Registry) error {

	if err := validate.Required("postTransactionsDepositOK"+"."+"status", "body", o.Status); err != nil {
		return err
	}

	// value enum
	if err := o.validateStatusEnum("postTransactionsDepositOK"+"."+"status", "body", *o.Status); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this post transactions deposit o k body based on context it is used
func (o *PostTransactionsDepositOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostTransactionsDepositOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostTransactionsDepositOKBody) UnmarshalBinary(b []byte) error {
	var res PostTransactionsDepositOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
