// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"encoding/json"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"github.com/h4x4d/crypto-market/main/internal/models"
)

// PostTransactionsWithdrawHandlerFunc turns a function with the right signature into a post transactions withdraw handler
type PostTransactionsWithdrawHandlerFunc func(PostTransactionsWithdrawParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn PostTransactionsWithdrawHandlerFunc) Handle(params PostTransactionsWithdrawParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// PostTransactionsWithdrawHandler interface for that can handle valid post transactions withdraw params
type PostTransactionsWithdrawHandler interface {
	Handle(PostTransactionsWithdrawParams, *models.User) middleware.Responder
}

// NewPostTransactionsWithdraw creates a new http.Handler for the post transactions withdraw operation
func NewPostTransactionsWithdraw(ctx *middleware.Context, handler PostTransactionsWithdrawHandler) *PostTransactionsWithdraw {
	return &PostTransactionsWithdraw{Context: ctx, Handler: handler}
}

/*
	PostTransactionsWithdraw swagger:route POST /transactions/withdraw postTransactionsWithdraw

# Withdrawal request

Creates a request to withdraw cryptocurrency from the user's account
*/
type PostTransactionsWithdraw struct {
	Context *middleware.Context
	Handler PostTransactionsWithdrawHandler
}

func (o *PostTransactionsWithdraw) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostTransactionsWithdrawParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// PostTransactionsWithdrawBody post transactions withdraw body
//
// swagger:model PostTransactionsWithdrawBody
type PostTransactionsWithdrawBody struct {

	// address
	// Example: 0x1234567890abcdef1234567890abcdef12345678
	// Required: true
	Address *string `json:"address"`

	// amount
	// Example: 100.5
	// Required: true
	// Minimum: 0
	// Multiple Of: 1e-08
	Amount *float32 `json:"amount"`

	// currency
	// Example: USDT
	// Required: true
	// Enum: ["USDT","BTC"]
	Currency *string `json:"currency"`
}

// Validate validates this post transactions withdraw body
func (o *PostTransactionsWithdrawBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateAddress(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateAmount(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateCurrency(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostTransactionsWithdrawBody) validateAddress(formats strfmt.Registry) error {

	if err := validate.Required("body"+"."+"address", "body", o.Address); err != nil {
		return err
	}

	return nil
}

func (o *PostTransactionsWithdrawBody) validateAmount(formats strfmt.Registry) error {

	if err := validate.Required("body"+"."+"amount", "body", o.Amount); err != nil {
		return err
	}

	if err := validate.Minimum("body"+"."+"amount", "body", float64(*o.Amount), 0, false); err != nil {
		return err
	}

	if err := validate.MultipleOf("body"+"."+"amount", "body", float64(*o.Amount), 1e-08); err != nil {
		return err
	}

	return nil
}

var postTransactionsWithdrawBodyTypeCurrencyPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["USDT","BTC"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		postTransactionsWithdrawBodyTypeCurrencyPropEnum = append(postTransactionsWithdrawBodyTypeCurrencyPropEnum, v)
	}
}

const (

	// PostTransactionsWithdrawBodyCurrencyUSDT captures enum value "USDT"
	PostTransactionsWithdrawBodyCurrencyUSDT string = "USDT"

	// PostTransactionsWithdrawBodyCurrencyBTC captures enum value "BTC"
	PostTransactionsWithdrawBodyCurrencyBTC string = "BTC"
)

// prop value enum
func (o *PostTransactionsWithdrawBody) validateCurrencyEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, postTransactionsWithdrawBodyTypeCurrencyPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (o *PostTransactionsWithdrawBody) validateCurrency(formats strfmt.Registry) error {

	if err := validate.Required("body"+"."+"currency", "body", o.Currency); err != nil {
		return err
	}

	// value enum
	if err := o.validateCurrencyEnum("body"+"."+"currency", "body", *o.Currency); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this post transactions withdraw body based on context it is used
func (o *PostTransactionsWithdrawBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostTransactionsWithdrawBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostTransactionsWithdrawBody) UnmarshalBinary(b []byte) error {
	var res PostTransactionsWithdrawBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
