// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Continuous market API for cryptocurrency trading and account management",
    "title": "market.main",
    "version": "0.1.0"
  },
  "paths": {
    "/account/balance": {
      "get": {
        "security": [
          {
            "api_key": []
          }
        ],
        "description": "Returns balance of all cryptocurrencies for the authenticated user",
        "produces": [
          "application/json"
        ],
        "summary": "Get user's balance",
        "responses": {
          "200": {
            "description": "Successful operation",
            "schema": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "amount": {
                    "type": "number",
                    "format": "float",
                    "example": 100.5
                  },
                  "currency": {
                    "type": "string",
                    "enum": [
                      "USDT",
                      "BTC"
                    ],
                    "example": "USDT"
                  }
                }
              },
              "example": [
                {
                  "amount": 100.5,
                  "currency": "USDT"
                },
                {
                  "amount": 0.005,
                  "currency": "BTC"
                }
              ]
            }
          },
          "401": {
            "description": "Unauthorized",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/bid": {
      "get": {
        "security": [
          {
            "api_key": []
          }
        ],
        "produces": [
          "application/json"
        ],
        "summary": "Get my bids",
        "operationId": "get_bids",
        "responses": {
          "200": {
            "description": "Successful operation",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/bid"
              }
            }
          },
          "403": {
            "description": "No access",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "post": {
        "security": [
          {
            "api_key": []
          }
        ],
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "summary": "Create bid",
        "operationId": "create_bid",
        "parameters": [
          {
            "name": "object",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/bid"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "schema": {
              "type": "object",
              "properties": {
                "bid_id": {
                  "type": "integer",
                  "format": "int64"
                }
              }
            }
          },
          "400": {
            "description": "Incorrect data",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "403": {
            "description": "No access",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/market/{bid_id}": {
      "get": {
        "security": [
          {
            "api_key": []
          }
        ],
        "produces": [
          "application/json"
        ],
        "summary": "Get bid info by id",
        "operationId": "get_bid_by_id",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "ID of bid to return",
            "name": "bid_id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "schema": {
              "$ref": "#/definitions/bid"
            }
          },
          "403": {
            "description": "No access",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "404": {
            "description": "Bid not found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "delete": {
        "security": [
          {
            "api_key": []
          }
        ],
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "summary": "Cancel bid",
        "operationId": "cancel_bid",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "ID of bid to cancel",
            "name": "bid_id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "schema": {
              "$ref": "#/definitions/Result"
            }
          },
          "400": {
            "description": "Incorrect data",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "403": {
            "description": "No access",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/metrics": {
      "get": {
        "description": "Returns Prometheus-compatible metrics for the service",
        "produces": [
          "text/plain; version=0.0.4"
        ],
        "summary": "Prometheus metrics",
        "responses": {
          "200": {
            "description": "Successful operation",
            "schema": {
              "type": "string",
              "example": "# HELP api_requests_total Total number of API requests\n# TYPE api_requests_total counter\napi_requests_total{method=\"POST\",endpoint=\"/transactions/deposit\"} 100\n"
            }
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/transactions/deposit": {
      "post": {
        "security": [
          {
            "api_key": []
          }
        ],
        "description": "Creates a request to deposit cryptocurrency to the user's account",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "summary": "Deposit request",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "required": [
                "currency",
                "amount"
              ],
              "properties": {
                "amount": {
                  "type": "number",
                  "format": "float",
                  "example": 100.5
                },
                "currency": {
                  "type": "string",
                  "enum": [
                    "USDT",
                    "BTC"
                  ],
                  "example": "USDT"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "schema": {
              "type": "object",
              "required": [
                "id",
                "status",
                "address"
              ],
              "properties": {
                "address": {
                  "type": "string",
                  "example": "0x1234567890abcdef1234567890abcdef12345678"
                },
                "id": {
                  "type": "string",
                  "example": "tx_dep_123456"
                },
                "status": {
                  "type": "string",
                  "enum": [
                    "finished",
                    "processing",
                    "pending"
                  ],
                  "example": "pending"
                }
              },
              "example": {
                "address": "0x1234567890abcdef1234567890abcdef12345678",
                "id": "tx_dep_123456",
                "status": "pending"
              }
            }
          },
          "400": {
            "description": "Incorrect data",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "401": {
            "description": "Unauthorized",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/transactions/purchase": {
      "get": {
        "security": [
          {
            "api_key": []
          }
        ],
        "description": "Returns the user's purchase history with optional filters",
        "produces": [
          "application/json"
        ],
        "summary": "Get purchase history",
        "parameters": [
          {
            "enum": [
              "finished",
              "processing",
              "cancelled"
            ],
            "type": "string",
            "description": "Filter by purchase status",
            "name": "status",
            "in": "query"
          },
          {
            "type": "string",
            "format": "date-time",
            "description": "Filter purchases from this date (ISO 8601)",
            "name": "date_from",
            "in": "query"
          },
          {
            "type": "string",
            "format": "date-time",
            "description": "Filter purchases up to this date (ISO 8601)",
            "name": "date_to",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "schema": {
              "type": "array",
              "items": {
                "type": "object",
                "required": [
                  "id",
                  "currency_from",
                  "currency_to",
                  "amount_from",
                  "amount_to",
                  "status",
                  "date"
                ],
                "properties": {
                  "amount_from": {
                    "type": "number",
                    "format": "float",
                    "example": 100.5
                  },
                  "amount_to": {
                    "type": "number",
                    "format": "float",
                    "example": 0.005
                  },
                  "currency_from": {
                    "type": "string",
                    "enum": [
                      "USDT",
                      "BTC"
                    ],
                    "example": "USDT"
                  },
                  "currency_to": {
                    "type": "string",
                    "enum": [
                      "USDT",
                      "BTC"
                    ],
                    "example": "BTC"
                  },
                  "date": {
                    "type": "string",
                    "format": "date-time",
                    "example": "2025-04-13T10:00:00Z"
                  },
                  "id": {
                    "type": "string",
                    "example": "pur_123456"
                  },
                  "status": {
                    "type": "string",
                    "enum": [
                      "finished",
                      "processing",
                      "cancelled"
                    ],
                    "example": "finished"
                  }
                }
              },
              "example": [
                {
                  "amount_from": 100.5,
                  "amount_to": 0.005,
                  "currency_from": "USDT",
                  "currency_to": "BTC",
                  "date": "2025-04-13T10:00:00Z",
                  "id": "pur_123456",
                  "status": "finished"
                }
              ]
            }
          },
          "400": {
            "description": "Incorrect data",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "401": {
            "description": "Unauthorized",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/transactions/transfers": {
      "get": {
        "security": [
          {
            "api_key": []
          }
        ],
        "description": "Returns the user's withdrawal and deposit history with optional filters",
        "produces": [
          "application/json"
        ],
        "summary": "Get withdrawal and deposit history",
        "parameters": [
          {
            "type": "number",
            "format": "float",
            "description": "Minimum transaction amount",
            "name": "min_amount",
            "in": "query"
          },
          {
            "type": "number",
            "format": "float",
            "description": "Maximum transaction amount",
            "name": "max_amount",
            "in": "query"
          },
          {
            "enum": [
              "finished",
              "processing",
              "cancelled",
              "pending"
            ],
            "type": "string",
            "description": "Filter by transaction status",
            "name": "status",
            "in": "query"
          },
          {
            "enum": [
              "USDT",
              "BTC"
            ],
            "type": "string",
            "description": "Filter by currency",
            "name": "currency",
            "in": "query"
          },
          {
            "enum": [
              "deposit",
              "withdraw"
            ],
            "type": "string",
            "description": "Filter by operation type",
            "name": "operation",
            "in": "query"
          },
          {
            "type": "string",
            "format": "date-time",
            "description": "Filter transactions from this date (ISO 8601)",
            "name": "date_from",
            "in": "query"
          },
          {
            "type": "string",
            "format": "date-time",
            "description": "Filter transactions up to this date (ISO 8601)",
            "name": "date_to",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "schema": {
              "type": "array",
              "items": {
                "type": "object",
                "required": [
                  "id",
                  "currency",
                  "amount",
                  "operation",
                  "status",
                  "date"
                ],
                "properties": {
                  "address": {
                    "type": "string",
                    "example": "0x1234567890abcdef1234567890abcdef12345678"
                  },
                  "amount": {
                    "type": "number",
                    "format": "float",
                    "example": 100.5
                  },
                  "commission": {
                    "type": "number",
                    "format": "float",
                    "example": 0.1
                  },
                  "currency": {
                    "type": "string",
                    "enum": [
                      "USDT",
                      "BTC"
                    ],
                    "example": "USDT"
                  },
                  "date": {
                    "type": "string",
                    "format": "date-time",
                    "example": "2025-04-13T10:00:00Z"
                  },
                  "id": {
                    "type": "string",
                    "example": "tx_dep_123456"
                  },
                  "operation": {
                    "type": "string",
                    "enum": [
                      "deposit",
                      "withdrawal"
                    ],
                    "example": "deposit"
                  },
                  "status": {
                    "type": "string",
                    "enum": [
                      "finished",
                      "processing",
                      "cancelled",
                      "pending"
                    ],
                    "example": "finished"
                  }
                }
              },
              "example": [
                {
                  "address": "0x1234567890abcdef1234567890abcdef12345678",
                  "amount": 100.5,
                  "commission": 0,
                  "currency": "USDT",
                  "date": "2025-04-13T10:00:00Z",
                  "id": "tx_dep_123456",
                  "operation": "deposit",
                  "status": "finished"
                }
              ]
            }
          },
          "400": {
            "description": "Incorrect data",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "401": {
            "description": "Unauthorized",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/transactions/withdraw": {
      "post": {
        "security": [
          {
            "api_key": []
          }
        ],
        "description": "Creates a request to withdraw cryptocurrency from the user's account",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "summary": "Withdrawal request",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "required": [
                "currency",
                "amount",
                "address"
              ],
              "properties": {
                "address": {
                  "type": "string",
                  "example": "0x1234567890abcdef1234567890abcdef12345678"
                },
                "amount": {
                  "type": "number",
                  "format": "float",
                  "example": 100.5
                },
                "currency": {
                  "type": "string",
                  "enum": [
                    "USDT",
                    "BTC"
                  ],
                  "example": "USDT"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "schema": {
              "type": "object",
              "required": [
                "id",
                "status",
                "tx_hash"
              ],
              "properties": {
                "commission": {
                  "type": "number",
                  "format": "float",
                  "example": 0.1
                },
                "id": {
                  "type": "string",
                  "example": "tx_with_123456"
                },
                "status": {
                  "type": "string",
                  "enum": [
                    "finished",
                    "processing",
                    "pending"
                  ],
                  "example": "pending"
                },
                "tx_hash": {
                  "type": "string",
                  "example": "0xabcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890"
                }
              },
              "example": {
                "commission": 0.1,
                "id": "tx_with_123456",
                "status": "pending",
                "tx_hash": "0xabcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890"
              }
            }
          },
          "400": {
            "description": "Incorrect data or insufficient balance",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "401": {
            "description": "Unauthorized",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Error": {
      "type": "object",
      "required": [
        "error_message",
        "error_status_code"
      ],
      "properties": {
        "error_message": {
          "type": "string",
          "example": "Invalid input data"
        },
        "error_status_code": {
          "type": "integer",
          "example": 400
        }
      }
    },
    "Result": {
      "type": "object",
      "properties": {
        "message": {
          "type": "string"
        },
        "status": {
          "type": "string"
        }
      }
    },
    "bid": {
      "type": "object",
      "properties": {
        "amount_to_buy": {
          "type": "number",
          "multipleOf": 1e-7
        },
        "bid_id": {
          "type": "integer",
          "format": "int64"
        },
        "bought_amount": {
          "type": "number",
          "multipleOf": 1e-7
        },
        "buy_speed": {
          "type": "number",
          "multipleOf": 1e-7
        },
        "max_price": {
          "type": "number",
          "multipleOf": 1e-7
        },
        "min_price": {
          "type": "number",
          "multipleOf": 1e-7
        },
        "user_id": {
          "type": "integer",
          "format": "int64"
        }
      }
    }
  },
  "securityDefinitions": {
    "api_key": {
      "type": "apiKey",
      "name": "api_key",
      "in": "header"
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Continuous market API for cryptocurrency trading and account management",
    "title": "market.main",
    "version": "0.1.0"
  },
  "paths": {
    "/account/balance": {
      "get": {
        "security": [
          {
            "api_key": []
          }
        ],
        "description": "Returns balance of all cryptocurrencies for the authenticated user",
        "produces": [
          "application/json"
        ],
        "summary": "Get user's balance",
        "responses": {
          "200": {
            "description": "Successful operation",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/GetAccountBalanceOKBodyItems0"
              },
              "example": [
                {
                  "amount": 100.5,
                  "currency": "USDT"
                },
                {
                  "amount": 0.005,
                  "currency": "BTC"
                }
              ]
            }
          },
          "401": {
            "description": "Unauthorized",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/bid": {
      "get": {
        "security": [
          {
            "api_key": []
          }
        ],
        "produces": [
          "application/json"
        ],
        "summary": "Get my bids",
        "operationId": "get_bids",
        "responses": {
          "200": {
            "description": "Successful operation",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/bid"
              }
            }
          },
          "403": {
            "description": "No access",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "post": {
        "security": [
          {
            "api_key": []
          }
        ],
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "summary": "Create bid",
        "operationId": "create_bid",
        "parameters": [
          {
            "name": "object",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/bid"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "schema": {
              "type": "object",
              "properties": {
                "bid_id": {
                  "type": "integer",
                  "format": "int64"
                }
              }
            }
          },
          "400": {
            "description": "Incorrect data",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "403": {
            "description": "No access",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/market/{bid_id}": {
      "get": {
        "security": [
          {
            "api_key": []
          }
        ],
        "produces": [
          "application/json"
        ],
        "summary": "Get bid info by id",
        "operationId": "get_bid_by_id",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "ID of bid to return",
            "name": "bid_id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "schema": {
              "$ref": "#/definitions/bid"
            }
          },
          "403": {
            "description": "No access",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "404": {
            "description": "Bid not found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "delete": {
        "security": [
          {
            "api_key": []
          }
        ],
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "summary": "Cancel bid",
        "operationId": "cancel_bid",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "ID of bid to cancel",
            "name": "bid_id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "schema": {
              "$ref": "#/definitions/Result"
            }
          },
          "400": {
            "description": "Incorrect data",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "403": {
            "description": "No access",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/metrics": {
      "get": {
        "description": "Returns Prometheus-compatible metrics for the service",
        "produces": [
          "text/plain; version=0.0.4"
        ],
        "summary": "Prometheus metrics",
        "responses": {
          "200": {
            "description": "Successful operation",
            "schema": {
              "type": "string",
              "example": "# HELP api_requests_total Total number of API requests\n# TYPE api_requests_total counter\napi_requests_total{method=\"POST\",endpoint=\"/transactions/deposit\"} 100\n"
            }
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/transactions/deposit": {
      "post": {
        "security": [
          {
            "api_key": []
          }
        ],
        "description": "Creates a request to deposit cryptocurrency to the user's account",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "summary": "Deposit request",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "required": [
                "currency",
                "amount"
              ],
              "properties": {
                "amount": {
                  "type": "number",
                  "format": "float",
                  "minimum": 0,
                  "example": 100.5
                },
                "currency": {
                  "type": "string",
                  "enum": [
                    "USDT",
                    "BTC"
                  ],
                  "example": "USDT"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "schema": {
              "type": "object",
              "required": [
                "id",
                "status",
                "address"
              ],
              "properties": {
                "address": {
                  "type": "string",
                  "example": "0x1234567890abcdef1234567890abcdef12345678"
                },
                "id": {
                  "type": "string",
                  "example": "tx_dep_123456"
                },
                "status": {
                  "type": "string",
                  "enum": [
                    "finished",
                    "processing",
                    "pending"
                  ],
                  "example": "pending"
                }
              },
              "example": {
                "address": "0x1234567890abcdef1234567890abcdef12345678",
                "id": "tx_dep_123456",
                "status": "pending"
              }
            }
          },
          "400": {
            "description": "Incorrect data",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "401": {
            "description": "Unauthorized",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/transactions/purchase": {
      "get": {
        "security": [
          {
            "api_key": []
          }
        ],
        "description": "Returns the user's purchase history with optional filters",
        "produces": [
          "application/json"
        ],
        "summary": "Get purchase history",
        "parameters": [
          {
            "enum": [
              "finished",
              "processing",
              "cancelled"
            ],
            "type": "string",
            "description": "Filter by purchase status",
            "name": "status",
            "in": "query"
          },
          {
            "type": "string",
            "format": "date-time",
            "description": "Filter purchases from this date (ISO 8601)",
            "name": "date_from",
            "in": "query"
          },
          {
            "type": "string",
            "format": "date-time",
            "description": "Filter purchases up to this date (ISO 8601)",
            "name": "date_to",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/GetTransactionsPurchaseOKBodyItems0"
              },
              "example": [
                {
                  "amount_from": 100.5,
                  "amount_to": 0.005,
                  "currency_from": "USDT",
                  "currency_to": "BTC",
                  "date": "2025-04-13T10:00:00Z",
                  "id": "pur_123456",
                  "status": "finished"
                }
              ]
            }
          },
          "400": {
            "description": "Incorrect data",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "401": {
            "description": "Unauthorized",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/transactions/transfers": {
      "get": {
        "security": [
          {
            "api_key": []
          }
        ],
        "description": "Returns the user's withdrawal and deposit history with optional filters",
        "produces": [
          "application/json"
        ],
        "summary": "Get withdrawal and deposit history",
        "parameters": [
          {
            "minimum": 0,
            "type": "number",
            "format": "float",
            "description": "Minimum transaction amount",
            "name": "min_amount",
            "in": "query"
          },
          {
            "minimum": 0,
            "type": "number",
            "format": "float",
            "description": "Maximum transaction amount",
            "name": "max_amount",
            "in": "query"
          },
          {
            "enum": [
              "finished",
              "processing",
              "cancelled",
              "pending"
            ],
            "type": "string",
            "description": "Filter by transaction status",
            "name": "status",
            "in": "query"
          },
          {
            "enum": [
              "USDT",
              "BTC"
            ],
            "type": "string",
            "description": "Filter by currency",
            "name": "currency",
            "in": "query"
          },
          {
            "enum": [
              "deposit",
              "withdraw"
            ],
            "type": "string",
            "description": "Filter by operation type",
            "name": "operation",
            "in": "query"
          },
          {
            "type": "string",
            "format": "date-time",
            "description": "Filter transactions from this date (ISO 8601)",
            "name": "date_from",
            "in": "query"
          },
          {
            "type": "string",
            "format": "date-time",
            "description": "Filter transactions up to this date (ISO 8601)",
            "name": "date_to",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/GetTransactionsTransfersOKBodyItems0"
              },
              "example": [
                {
                  "address": "0x1234567890abcdef1234567890abcdef12345678",
                  "amount": 100.5,
                  "commission": 0,
                  "currency": "USDT",
                  "date": "2025-04-13T10:00:00Z",
                  "id": "tx_dep_123456",
                  "operation": "deposit",
                  "status": "finished"
                }
              ]
            }
          },
          "400": {
            "description": "Incorrect data",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "401": {
            "description": "Unauthorized",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/transactions/withdraw": {
      "post": {
        "security": [
          {
            "api_key": []
          }
        ],
        "description": "Creates a request to withdraw cryptocurrency from the user's account",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "summary": "Withdrawal request",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "required": [
                "currency",
                "amount",
                "address"
              ],
              "properties": {
                "address": {
                  "type": "string",
                  "example": "0x1234567890abcdef1234567890abcdef12345678"
                },
                "amount": {
                  "type": "number",
                  "format": "float",
                  "minimum": 0,
                  "example": 100.5
                },
                "currency": {
                  "type": "string",
                  "enum": [
                    "USDT",
                    "BTC"
                  ],
                  "example": "USDT"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "schema": {
              "type": "object",
              "required": [
                "id",
                "status",
                "tx_hash"
              ],
              "properties": {
                "commission": {
                  "type": "number",
                  "format": "float",
                  "minimum": 0,
                  "example": 0.1
                },
                "id": {
                  "type": "string",
                  "example": "tx_with_123456"
                },
                "status": {
                  "type": "string",
                  "enum": [
                    "finished",
                    "processing",
                    "pending"
                  ],
                  "example": "pending"
                },
                "tx_hash": {
                  "type": "string",
                  "example": "0xabcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890"
                }
              },
              "example": {
                "commission": 0.1,
                "id": "tx_with_123456",
                "status": "pending",
                "tx_hash": "0xabcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890"
              }
            }
          },
          "400": {
            "description": "Incorrect data or insufficient balance",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "401": {
            "description": "Unauthorized",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Error": {
      "type": "object",
      "required": [
        "error_message",
        "error_status_code"
      ],
      "properties": {
        "error_message": {
          "type": "string",
          "example": "Invalid input data"
        },
        "error_status_code": {
          "type": "integer",
          "example": 400
        }
      }
    },
    "GetAccountBalanceOKBodyItems0": {
      "type": "object",
      "properties": {
        "amount": {
          "type": "number",
          "format": "float",
          "minimum": 0,
          "example": 100.5
        },
        "currency": {
          "type": "string",
          "enum": [
            "USDT",
            "BTC"
          ],
          "example": "USDT"
        }
      }
    },
    "GetTransactionsPurchaseOKBodyItems0": {
      "type": "object",
      "required": [
        "id",
        "currency_from",
        "currency_to",
        "amount_from",
        "amount_to",
        "status",
        "date"
      ],
      "properties": {
        "amount_from": {
          "type": "number",
          "format": "float",
          "minimum": 0,
          "example": 100.5
        },
        "amount_to": {
          "type": "number",
          "format": "float",
          "minimum": 0,
          "example": 0.005
        },
        "currency_from": {
          "type": "string",
          "enum": [
            "USDT",
            "BTC"
          ],
          "example": "USDT"
        },
        "currency_to": {
          "type": "string",
          "enum": [
            "USDT",
            "BTC"
          ],
          "example": "BTC"
        },
        "date": {
          "type": "string",
          "format": "date-time",
          "example": "2025-04-13T10:00:00Z"
        },
        "id": {
          "type": "string",
          "example": "pur_123456"
        },
        "status": {
          "type": "string",
          "enum": [
            "finished",
            "processing",
            "cancelled"
          ],
          "example": "finished"
        }
      }
    },
    "GetTransactionsTransfersOKBodyItems0": {
      "type": "object",
      "required": [
        "id",
        "currency",
        "amount",
        "operation",
        "status",
        "date"
      ],
      "properties": {
        "address": {
          "type": "string",
          "example": "0x1234567890abcdef1234567890abcdef12345678"
        },
        "amount": {
          "type": "number",
          "format": "float",
          "minimum": 0,
          "example": 100.5
        },
        "commission": {
          "type": "number",
          "format": "float",
          "minimum": 0,
          "example": 0.1
        },
        "currency": {
          "type": "string",
          "enum": [
            "USDT",
            "BTC"
          ],
          "example": "USDT"
        },
        "date": {
          "type": "string",
          "format": "date-time",
          "example": "2025-04-13T10:00:00Z"
        },
        "id": {
          "type": "string",
          "example": "tx_dep_123456"
        },
        "operation": {
          "type": "string",
          "enum": [
            "deposit",
            "withdrawal"
          ],
          "example": "deposit"
        },
        "status": {
          "type": "string",
          "enum": [
            "finished",
            "processing",
            "cancelled",
            "pending"
          ],
          "example": "finished"
        }
      }
    },
    "Result": {
      "type": "object",
      "properties": {
        "message": {
          "type": "string"
        },
        "status": {
          "type": "string"
        }
      }
    },
    "bid": {
      "type": "object",
      "properties": {
        "amount_to_buy": {
          "type": "number",
          "multipleOf": 1e-7
        },
        "bid_id": {
          "type": "integer",
          "format": "int64"
        },
        "bought_amount": {
          "type": "number",
          "multipleOf": 1e-7
        },
        "buy_speed": {
          "type": "number",
          "multipleOf": 1e-7
        },
        "max_price": {
          "type": "number",
          "multipleOf": 1e-7
        },
        "min_price": {
          "type": "number",
          "multipleOf": 1e-7
        },
        "user_id": {
          "type": "integer",
          "format": "int64"
        }
      }
    }
  },
  "securityDefinitions": {
    "api_key": {
      "type": "apiKey",
      "name": "api_key",
      "in": "header"
    }
  }
}`))
}
