// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// WithdrawResponse withdraw response
//
// swagger:model withdraw_response
type WithdrawResponse struct {

	// commission
	// Example: 0.1
	// Minimum: 0
	// Multiple Of: 1e-08
	Commission *float32 `json:"commission,omitempty"`

	// id
	// Example: tx_with_123456
	// Required: true
	ID *string `json:"id"`

	// status
	// Example: pending
	// Required: true
	// Enum: ["finished","processing","pending"]
	Status *string `json:"status"`

	// tx hash
	// Example: 0xabcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890
	TxHash string `json:"tx_hash,omitempty"`
}

// Validate validates this withdraw response
func (m *WithdrawResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCommission(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *WithdrawResponse) validateCommission(formats strfmt.Registry) error {
	if swag.IsZero(m.Commission) { // not required
		return nil
	}

	if err := validate.Minimum("commission", "body", float64(*m.Commission), 0, false); err != nil {
		return err
	}

	if err := validate.MultipleOf("commission", "body", float64(*m.Commission), 1e-08); err != nil {
		return err
	}

	return nil
}

func (m *WithdrawResponse) validateID(formats strfmt.Registry) error {

	if err := validate.Required("id", "body", m.ID); err != nil {
		return err
	}

	return nil
}

var withdrawResponseTypeStatusPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["finished","processing","pending"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		withdrawResponseTypeStatusPropEnum = append(withdrawResponseTypeStatusPropEnum, v)
	}
}

const (

	// WithdrawResponseStatusFinished captures enum value "finished"
	WithdrawResponseStatusFinished string = "finished"

	// WithdrawResponseStatusProcessing captures enum value "processing"
	WithdrawResponseStatusProcessing string = "processing"

	// WithdrawResponseStatusPending captures enum value "pending"
	WithdrawResponseStatusPending string = "pending"
)

// prop value enum
func (m *WithdrawResponse) validateStatusEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, withdrawResponseTypeStatusPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *WithdrawResponse) validateStatus(formats strfmt.Registry) error {

	if err := validate.Required("status", "body", m.Status); err != nil {
		return err
	}

	// value enum
	if err := m.validateStatusEnum("status", "body", *m.Status); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this withdraw response based on context it is used
func (m *WithdrawResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *WithdrawResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WithdrawResponse) UnmarshalBinary(b []byte) error {
	var res WithdrawResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
